### ISSUE TITLE
Could you please upload the mnist data file (dataset_fly_64x64_lines_train.t7')?

### ISSUE THREAD

**Issue by jundeng86** [viorik/ConvLSTM#1]
Hi Viorik,

Thanks for sharing  the code. In order to run the code, could you please also share the data used? 
Thanks!!!

**Comment by viorik** [comment]
Hi @jundeng86 
I added a link to the dataset on the main page of the project.

**Comment by jundeng86** [comment]
Hi Viorik,

Thanks for your help!
But that link may not be available publicly (the page I read is shown below). Could you please fix it? Thank very much!
Jun

![screenshot from 2015-12-30 10 57 04](https://cloud.githubusercontent.com/assets/8589835/12049184/4e767014-aee4-11e5-94ff-7b0f661957eb.png)

**Comment by viorik** [comment]
@jundeng86 Are you using Chrome? Could you try opening the page with Firefox? Normally the page is publicly available, but there might be some browser issue that I don't get yet. I'll try to see what happens for Chrome.

**Comment by jundeng86** [comment]
Hi Viorik,

Thanks for your continual help.  It works with Chrome. I was opening the page with Firefox, :).
Thanks again for your time.
Best,
Jun
