### ISSUE TITLE
Can not read dataset file

### ISSUE THREAD

**Issue by sodabeta7** [viorik/ConvLSTM#10]
Hi,
When I try to run ``main-mnist.lua``, following errors happened:
```
/home/sodabeta/torch/install/bin/luajit: /home/sodabeta/torch/install/share/lua/5.1/torch/File.lua:366: unknown object
stack traceback:
        [C]: in function 'error'
        /home/sodabeta/torch/install/share/lua/5.1/torch/File.lua:366: in function 'readObject'
        /home/sodabeta/torch/install/share/lua/5.1/torch/File.lua:391: in function 'load'
        /home/sodabeta/convlstm/ConvLSTM/data-mnist.lua:4: in function 'getdataSeq_mnist'
        main-mnist.lua:23: in function 'main'
        main-mnist.lua:162: in main chunk
        [C]: in function 'dofile'
        ...beta/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670
```
I downloaded the dataset file from the link provided, and I'm not sure if the downloaded dataset file is broken, and it should be helpful if you could provide the md5sum.
Please let me know if you have any ideas about the problem. Thanks!

**Comment by viorik** [comment]
Hi @sodabeta7,
The problem might have been that I recently changed the code to load the data in binary format (which is faster), but the dataset online is still in ascii format. I now added back the initial command to read the data in ascii. Could you, please, try again and let me know if it works? Thank you.

**Comment by sodabeta7** [comment]
It works now, thanks! @viorik
