### ISSUE TITLE
Miss match Tensor Size between input2gate and output2gate

### ISSUE THREAD

**Issue by saix47** [viorik/ConvLSTM#15]
Hello @viorik ,
As I understand,  in function buildGate(), input2gate and output2gate only have same size if you setting the stride = 1 (then the width and height of input will be preserved). But in case the stride is not 1, then the input2gate and output2gate don't have same size. In your paper, you said the input is dxhxw and output is dmxhxw, this's only true if stride=1. Am I right?

**Comment by viorik** [comment]
Hi @saix47 

Indeed, currently the code works for stride=1, but to make it work for any stride I think you only need to adapt the size of the zero tensor used at step 1 as memory, lines 145-149.
I will think of updating this in the future to make it work for any stride.

cheers.

**Comment by saix47** [comment]
Hi @viorik ,
Thank you. I understand that.
