### ISSUE TITLE
UntiedConvLSTM: Error In Back-propagation 

### ISSUE THREAD

**Issue by rmalav15** [viorik/ConvLSTM#18]
I am getting following error while training Network containing UntiedConvLSTM()  

> ~/torch/install/share/lua/5.1/nn/ConcatTable.lua:55: bad argument #2 to 'add' (sizes do not match at /home/rmalav/torch/extra/cutorch/lib/THC/generic/THCTensorMathPointwise.cu:10)

After some testing, I found that network is unable to backpropogate (model:forward() works fine, But model:backward() throws above error). I have created a simple  [Jupyter Notebook File](http://nbviewer.jupyter.org/gist/rmalav15/8e09e1d3fa9db314d6102bd19c0ed95b) just to show the problem.

I think I am missing something obvious. Can you help me with it?
Thank You.

**Comment by viorik** [comment]
It seems to me the problem is coming from the fact that you are not specifying the batchsize. If you look in ConvLSTM (the parent of UntiedConvLSTM), the batchsize is set to nil by default. But for your input data, the batchsize should be explicitly set as 1. Hence use
`convlstm = nn.UntiedConvLSTM(3,3,6,3,5,1,1)`
Let me know if this helps.

**Comment by rmalav15** [comment]
Thank you so much @viorik.
It works now.

I thought its not mandatory to specify batch-size, as in "model-demo-ConvLSTM.lua" UntiedConvLSTM was initialized without it.

> net:add(nn.UntiedConvLSTM(opt.nFiltersMemory[1],opt.nFiltersMemory[2], opt.nSeq, opt.kernelSize, opt.kernelSizeMemory, opt.stride))

But again, I should have gone through constructor details of both novel layers.

**Comment by viorik** [comment]
It was initialised without batchsize since the data in that demo is not structured in batches, so there indeed the batchsize is nil.

**Comment by rmalav15** [comment]
Thanks again @viorik 
Its clear now.
