### ISSUE TITLE
Code not working with new rnn update

### ISSUE THREAD

**Issue by mansirankawat** [viorik/ConvLSTM#3]
Hi Viorik,

Your code is not compatible with new rnn update. Nicholas has tried update it but there is some issue with the extracunn's SpatialConvolutionMMNoBias. If you could help in figuring out why that error is coming then it will be great!

Thanks
Mansi

**Comment by zdx3578** [comment]
can you add more doc for how to run ?

**Comment by zdx3578** [comment]
trained on our modified version of moving MNIST dataset, available here. 
buth http://mi.eng.cam.ac.uk/~vp344/ no file to down

**Comment by viorik** [comment]
Thanks, @nicholas-leonard, for the PR. @mansirankawat, I am looking into this asap.

**Comment by viorik** [comment]
@zdx3578, could you please try opening the page with a different browser? There are some strange browser issues that I still didn't understand.

**Comment by zdx3578** [comment]
@viorik  thanks  http://mi.eng.cam.ac.uk/~vp344/ in chrome show nothing,but open with firefox is ok; thanks!

**Comment by viorik** [comment]
@mansirankawat I've updated ConvLSTM, hopefully it should run now. Let me know. Thanks.

**Comment by mansirankawat** [comment]
@viorik  Thanks its working now
